.gitignore
.pre-commit-config.yaml
schema/entities/access-platform.json
schema/entities/activity.json
schema/entities/contact-point.json
schema/entities/distribution.json
schema/entities/organizational-unit.json
schema/entities/person.json
schema/entities/resource.json
schema/entities/variable.json
setup.py

- make mex-model installable as a python distribution
- convert `activity.start` and `end` to arrays
- add `useScheme` to `Distribution.license`
- update examples to be inline with mex-common
- fix patterns to JSON-escape `\`
- fix typos

mex-model 2.1.1

---

.cruft.json
.github/workflows/cookiecutter.yml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/77ce51

Bump cookiecutter template to 77ce51

---

.cruft.json
.pre-commit-config.yaml
CODE_OF_CONDUCT.md

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/725373

Bump cookiecutter template to 725373

---

.cruft.json
.github/workflows/cookiecutter.yml
.github/workflows/cve-scan.yml
.github/workflows/documentation.yml
.github/workflows/linting.yml
.gitignore
Makefile
README.md
mex.bat

```diff a/README.md b/README.md	(rejected hunks)
@@ -75,16 +74,16 @@ components of the MEx project are open-sourced under the same license as well.
- update boilerplate files with `cruft update`
-- update global dependencies in `requirements.txt` manually
+- update global requirements in `requirements.txt` manually
- update git hooks with `pre-commit autoupdate`
- show outdated dependencies with `poetry show --outdated`
- update dependencies in poetry using `poetry update --lock`
-- update github actions manually in `.github/workflows/*.yml`
+- update github actions in `.github/workflows/*.yml` manually
-- update version, eg `poetry version minor`
-- commit update `git commit --message "..." pyproject.toml`
+- update version in `pyproject.toml` and `CHANGELOG.md`
+- commit update `git …
```

Bump cookiecutter template to a3eb74

---

.cruft.json
.github/workflows/cookiecutter.yml
.github/workflows/cve-scan.yml
.github/workflows/documentation.yml
.github/workflows/linting.yml
.github/workflows/open-code.yml
.github/workflows/release.yml
.github/workflows/renovatebot.yml
.github/workflows/reviewing.yml
.gitignore
.pre-commit-config.yaml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/71137c

Bump cookiecutter template to 71137c

---

.cruft.json
.pre-commit-config.yaml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/39db8b
```diff a/pyproject.toml b/pyproject.toml	(rejected hunks)
@@ -16,7 +16,7 @@ optional-dependencies.dev = [
"pytest-random-order==1.1.1",
"pytest-xdist==3.6.1",
"pytest==8.2.2",
-    "ruff==0.4.8",
+    "ruff==0.4.9",
"sphinx==7.3.7",
]
@@ -42,7 +42,7 @@ distribution = true
[tool.pdm.scripts]
update-all = { cmd = "pdm update --group :all --update-all --save-compatible" }
lock-all = { cmd = "pdm lock --group :all --refresh" }
-install-all = { cmd = "pdm install --group :all --no-editable --no-lock" }
+install-all = { cmd = "pdm install --group :all --frozen-lockfile" }
export-all = { cmd = "pdm export --group :all --no-hashes -f requirements" }
apidoc = { cmd = "pdm run sphinx-apidoc -f -o …
```

Bump cookiecutter template to 39db8b

---

.cruft.json
.pre-commit-config.yaml
README.md
pyproject.toml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/cf7f28
```diff a/pyproject.toml b/pyproject.toml	(rejected hunks)
@@ -9,15 +9,14 @@ urls = { Repository = "https://github.com/robert-koch-institut/mex-model" }
requires-python = "<3.13,>=3.11"
dependencies = []
optional-dependencies.dev = [
-    "black==24.4.2",
"ipdb==0.13.13",
-    "mypy==1.10.0",
+    "mypy==1.11.0",
"pytest-cov==5.0.0",
"pytest-random-order==1.1.1",
"pytest-xdist==3.6.1",
-    "pytest==8.2.2",
-    "ruff==0.4.9",
-    "sphinx==7.3.7",
+    "pytest==8.3.1",
+    "ruff==0.5.4",
+    "sphinx==7.4.0",
]
[project.scripts]
@@ -126,5 +129,5 @@ known-first-party = ["mex", "tests"]
convention = "google"
[build-system]
-requires = ["pdm-backend==2.3.0"]
+requires = …
```

Bump cookiecutter template to cf7f28

---

.cruft.json
.github/workflows/cve-scan.yml
.github/workflows/linting.yml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/20d79c
```diff a/.github/workflows/release.yml b/.github/workflows/release.yml	(rejected hunks)
@@ -88,7 +88,7 @@ jobs:
needs: release
steps:
- name: Build, tag and push docker image to ghcr
-        uses: GlueOps/github-actions-build-push-containers@v0.4.4
+        uses: GlueOps/github-actions-build-push-containers@v0.4.5
with:
tags: "${{ github.sha }},${{ needs.release.outputs.tag }},latest"
```
```diff a/.github/workflows/renovatebot.yml b/.github/workflows/renovatebot.yml	(rejected hunks)
fetch-depth: 1
-        uses: renovatebot/github-action@v40.2.4
+        uses: renovatebot/github-action@v40.2.5
env:
RENOVATE_GIT_PRIVATE_KEY: ${{ …
```

Bump cookiecutter template to 20d79c

---

.cruft.json

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/77775e
```diff a/.github/workflows/release.yml b/.github/workflows/release.yml	(rejected hunks)
@@ -127,7 +127,7 @@ jobs:
--tag ghcr.io/robert-koch-institut/mex-model:latest \
--tag ghcr.io/robert-koch-institut/mex-model:${{ github.sha }} \
--tag ghcr.io/robert-koch-institut/mex-model:${{ needs.release.outputs.tag }}
-          docker push ghcr.io/robert-koch-institut/mex-model:latest
+          docker push --all-tags ghcr.io/robert-koch-institut/mex-model:latest
distribute:
runs-on: ubuntu-latest
```

Bump cookiecutter template to 77775e

---

.cruft.json
.gitignore
.pre-commit-config.yaml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/916798
```diff a/requirements.txt b/requirements.txt	(rejected hunks)
@@ -1,5 +1,5 @@
cruft==2.15.0
mex-release @ git+https://github.com/robert-koch-institut/mex-release.git
-pdm==2.18.1
+pdm==2.19.1
pre-commit==3.8.0
wheel==0.44.0
```
```diff a/.github/workflows/release.yml b/.github/workflows/release.yml	(rejected hunks)
@@ -114,14 +114,14 @@ jobs:
run: |
pdm export --self --output locked-requirements.txt --no-hashes --without dev
-      - name: 'Login to GitHub Container Registry'
+      - name: Login to container registry
uses: docker/login-action@v3
with:
registry: ghcr.io
username: ${{github.actor}}
password: ${{secrets.GITHUB_TOKEN}}
-      - name: 'Build Inventory Image'
+      - name: …
```

Bump cookiecutter template to 916798

---

.cruft.json
README.md
pyproject.toml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/6c467f
```diff a/README.md b/README.md	(rejected hunks)
@@ -9,7 +9,7 @@ JSON schema files defining the MEx metadata model.
[![open-code](https://github.com/robert-koch-institut/mex-model/actions/workflows/open-code.yml/badge.svg)](https://gitlab.opencode.de/robert-koch-institut/mex/mex-model)
[![testing](https://github.com/robert-koch-institut/mex-model/actions/workflows/testing.yml/badge.svg)](https://github.com/robert-koch-institut/mex-model/actions/workflows/testing.yml)
-## project
+## Project
The Metadata Exchange (MEx) project is committed to improve the retrieval of RKI
research data and projects. How? By focusing on metadata: instead of providing the
@@ -55,14 +56,14 @@ translations of …
```

Bump cookiecutter template to 6c467f

---

.cruft.json

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/b0a205
```diff a/requirements.txt b/requirements.txt	(rejected hunks)
@@ -1,5 +1,5 @@
cruft==2.15.0
mex-release==0.3.0
-pdm==2.19.3
+pdm==2.20.0.post1
pre-commit==4.0.1
wheel==0.44.0
```
```diff a/.github/workflows/release.yml b/.github/workflows/release.yml	(rejected hunks)
@@ -59,6 +59,8 @@ jobs:
- name: Configure git
env:
+          MEX_BOT_EMAIL: ${{ vars.MEX_BOT_EMAIL }}
+          MEX_BOT_USER: ${{ vars.MEX_BOT_USER }}
SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
SIGNING_PUB: ${{ secrets.SIGNING_PUB }}
run: |
```
```diff a/.github/workflows/cookiecutter.yml b/.github/workflows/cookiecutter.yml	(rejected hunks)
@@ -48,6 +48,8 @@ jobs:
- name: Configure git
env:
+          MEX_BOT_EMAIL: ${{ …
```

Bump cookiecutter template to b0a205

---

CHANGELOG.md
mex/model/entities/distribution.json

We want to make all fields that have the name "title" of type text field.
type of field title in distribution, now it is a text field.

changed the type of the title field in distribution to be a text field

---

.cruft.json
.github/workflows/cookiecutter.yml
.github/workflows/documentation.yml
.github/workflows/linting.yml
.github/workflows/release.yml
.pre-commit-config.yaml
LICENSE

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/57e9b7
```diff a/.github/workflows/renovatebot.yml b/.github/workflows/renovatebot.yml	(rejected hunks)
fetch-depth: 1
-        uses: renovatebot/github-action@v41.0.2
+        uses: renovatebot/github-action@v41.0.8
env:
RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
RENOVATE_REPOSITORIES: "robert-koch-institut/mex-model"
```
```diff a/pyproject.toml b/pyproject.toml	(rejected hunks)
@@ -15,7 +15,7 @@ optional-dependencies.dev = [
"pytest-random-order>=1,<2",
"pytest-xdist>=3,<4",
"pytest>=8,<9",
-    "ruff>=0.7,<1",
+    "ruff>=0.9,<1",
"sphinx>=8,<9",
]
@@ -138,5 +138,5 @@ known-first-party = ["mex", "tests"]
convention = "google" …
```

Bump cookiecutter template to 57e9b7

---

.cruft.json
.github/pull_request_template.md
README.md

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/5446da

Bump cookiecutter template to 5446da

---

.cruft.json
.gitignore
.pre-commit-config.yaml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/8bdad0

Bump cookiecutter template to 8bdad0

---

.cruft.json
.github/workflows/release.yml
.gitignore
.pre-commit-config.yaml
docs/layout.html
requirements.txt

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/716a58
```diff a/pyproject.toml b/pyproject.toml	(rejected hunks)
@@ -11,7 +11,7 @@ dependencies = []
optional-dependencies.dev = [
"ipdb>=0.13,<1",
"mypy>=1,<2",
-    "pytest-cov>=5,<6",
+    "pytest-cov>=6,<7",
"pytest-random-order>=1,<2",
"pytest-xdist>=3,<4",
"pytest>=8,<9",
```
```diff a/.github/workflows/renovatebot.yml b/.github/workflows/renovatebot.yml	(rejected hunks)
fetch-depth: 1
-        uses: renovatebot/github-action@v41.0.13
+        uses: renovatebot/github-action@v41.0.14
env:
RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
RENOVATE_REPOSITORIES: "robert-koch-institut/mex-model"
```
```diff a/.pre-commit-config.yaml …
```

Bump cookiecutter template to 716a58

---

.cruft.json
.pre-commit-config.yaml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/08b84c
```diff a/.github/workflows/renovatebot.yml b/.github/workflows/renovatebot.yml	(rejected hunks)
fetch-depth: 1
-        uses: renovatebot/github-action@v41.0.14
+        uses: renovatebot/github-action@v41.0.21
env:
RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
RENOVATE_REPOSITORIES: "robert-koch-institut/mex-model"
```
```diff a/.pre-commit-config.yaml b/.pre-commit-config.yaml	(rejected hunks)
@@ -3,7 +3,7 @@ default_language_version:
python: python3.11
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
-    rev: v0.9.10
+    rev: v0.11.7
hooks:
- id: ruff
args: [--fix, --exit-non-zero-on-fix]
```
```diff …
```

Bump cookiecutter template to 08b84c

---

.cruft.json
.github/workflows/cookiecutter.yml
.github/workflows/documentation.yml
.github/workflows/linting.yml
.github/workflows/release.yml
.gitignore
docs/conf.py
pyproject.toml

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/ed5deb

Bump cookiecutter template to ed5deb

---

.cruft.json
.github/workflows/cookiecutter.yml
.github/workflows/documentation.yml
.github/workflows/linting.yml
.github/workflows/release.yml
.gitignore
.pre-commit-config.yaml
renovate.json

- bumped cookiecutter template to https://github.com/robert-koch-institut/mex-template/commit/e886ec
```diff a/.github/workflows/renovatebot.yml b/.github/workflows/renovatebot.yml	(rejected hunks)
fetch-depth: 1
-        uses: renovatebot/github-action@v42.0.5
+        uses: renovatebot/github-action@v43.0.3
env:
RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
RENOVATE_REPOSITORIES: "robert-koch-institut/mex-model"
```
```diff a/requirements.txt b/requirements.txt	(rejected hunks)
@@ -1,4 +1,4 @@
cruft==2.16.0
mex-release==0.3.3
-pdm==2.25.2
+pdm==2.25.4
pre-commit==4.2.0
```
```diff a/pyproject.toml b/pyproject.toml	(rejected hunks)
@@ -15,7 +15,7 @@ optional-dependencies.dev = [
"pytest-random-order>=1",
"pytest-xdist>=3", …
```

Bump cookiecutter template to e886ec
